"""Add max_users_override to Tenant

Revision ID: 00d8eac2e022
Revises: 9f7908afde2d
Create Date: 2026-02-20 22:44:22.885014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00d8eac2e022'
down_revision: Union[str, Sequence[str], None] = '9f7908afde2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tenant_users_user_id_fkey'), 'tenant_users', type_='foreignkey')
    op.drop_constraint(op.f('tenant_users_tenant_id_fkey'), 'tenant_users', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_users', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'tenant_users', 'saas_users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('tenants', sa.Column('max_users_override', sa.Integer(), nullable=True, comment='Sobrescribe el limite del plan'))
    op.drop_constraint(op.f('tenants_plan_id_fkey'), 'tenants', type_='foreignkey')
    op.create_foreign_key(None, 'tenants', 'saas_plans', ['plan_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tenants_plan_id_fkey'), 'tenants', 'saas_plans', ['plan_id'], ['id'])
    op.drop_column('tenants', 'max_users_override')
    op.drop_constraint(None, 'tenant_users', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'tenant_users', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tenant_users_tenant_id_fkey'), 'tenant_users', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(op.f('tenant_users_user_id_fkey'), 'tenant_users', 'saas_users', ['user_id'], ['id'])
    # ### end Alembic commands ###
