"""expand_tenant_with_dte_fields

Revision ID: 0ef96f03b890
Revises: 00d8eac2e022
Create Date: 2026-02-20 23:44:54.288266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ef96f03b890'
down_revision: Union[str, Sequence[str], None] = '00d8eac2e022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Explicitly target public schema for SaaS global tables
    op.add_column('tenants', sa.Column('address', sa.String(length=300), nullable=True), schema='public')
    op.add_column('tenants', sa.Column('commune', sa.String(length=100), nullable=True), schema='public')
    op.add_column('tenants', sa.Column('city', sa.String(length=100), nullable=True), schema='public')
    op.add_column('tenants', sa.Column('giro', sa.String(length=200), nullable=True), schema='public')
    op.add_column('tenants', sa.Column('billing_day', sa.Integer(), nullable=True, comment='Día del mes para pago/facturación'), schema='public')
    op.add_column('tenants', sa.Column('economic_activities', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True), schema='public')
    
    # Backfill billing_day for existing tenants
    op.execute("UPDATE public.tenants SET billing_day = 1 WHERE billing_day IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'economic_activities', schema='public')
    op.drop_column('tenants', 'billing_day', schema='public')
    op.drop_column('tenants', 'giro', schema='public')
    op.drop_column('tenants', 'city', schema='public')
    op.drop_column('tenants', 'commune', schema='public')
    op.drop_column('tenants', 'address', schema='public')
    # ### end Alembic commands ###
