"""Initial SaaS global models

Revision ID: 9f7908afde2d
Revises: 
Create Date: 2026-02-20 21:25:42.345700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f7908afde2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saas_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_monthly', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_saas_plans_id'), 'saas_plans', ['id'], unique=False, schema='public')
    op.create_table('saas_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True, comment='Admin del SaaS (nosotros)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_saas_users_email'), 'saas_users', ['email'], unique=True, schema='public')
    op.create_index(op.f('ix_public_saas_users_id'), 'saas_users', ['id'], unique=False, schema='public')
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=True),
    sa.Column('schema_name', sa.String(length=63), nullable=False, comment='Nombre del esquema en PG'),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['public.saas_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_tenants_id'), 'tenants', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_tenants_rut'), 'tenants', ['rut'], unique=True, schema='public')
    op.create_index(op.f('ix_public_tenants_schema_name'), 'tenants', ['schema_name'], unique=True, schema='public')
    op.create_table('tenant_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.saas_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_tenant_users_id'), 'tenant_users', ['id'], unique=False, schema='public')
    op.alter_column('products', 'codigo_interno',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='SKU / código interno del producto',
               existing_nullable=False)
    op.alter_column('products', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('products', 'precio_neto',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               comment=None,
               existing_comment='Precio sin IVA',
               existing_nullable=False)
    op.alter_column('products', 'costo_unitario',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               comment='Costo de adquisición para margen',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('products', 'unidad_medida',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='unidad, kg, lt, mt, etc.',
               existing_nullable=True)
    op.alter_column('products', 'codigo_barras',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               comment=None,
               existing_comment='Código de barras EAN/UPC',
               existing_nullable=True)
    op.alter_column('products', 'stock_actual',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=15, scale=4),
               existing_nullable=True)
    op.alter_column('products', 'stock_minimo',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=15, scale=4),
               existing_nullable=True)
    op.alter_column('products', 'parent_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID del producto padre (si es una variante)',
               existing_nullable=True)
    op.drop_index(op.f('ix_products_parent_id'), table_name='products')
    op.drop_index(op.f('ix_products_codigo_barras'), table_name='products')
    op.create_index(op.f('ix_products_codigo_barras'), 'products', ['codigo_barras'], unique=False)
    op.alter_column('roles', 'permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('sales', 'user_id',
               existing_type=sa.INTEGER(),
               comment='Legacy Seller ID',
               existing_nullable=False)
    op.alter_column('sales', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'stock_movements', 'users', ['user_id'], ['id'])
    op.drop_column('users', 'comuna')
    op.drop_column('users', 'ciudad')
    op.drop_column('users', 'giro')
    op.drop_column('users', 'direccion')
    op.drop_column('users', 'current_balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True, comment='Saldo de Cuenta Corriente (Positivo=Deuda)'))
    op.add_column('users', sa.Column('direccion', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('giro', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('ciudad', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('comuna', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.alter_column('sales', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sales', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Legacy Seller ID',
               existing_nullable=False)
    op.alter_column('roles', 'permissions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_products_codigo_barras'), table_name='products')
    op.create_index(op.f('ix_products_codigo_barras'), 'products', ['codigo_barras'], unique=True)
    op.create_index(op.f('ix_products_parent_id'), 'products', ['parent_id'], unique=False)
    op.alter_column('products', 'parent_id',
               existing_type=sa.INTEGER(),
               comment='ID del producto padre (si es una variante)',
               existing_nullable=True)
    op.alter_column('products', 'stock_minimo',
               existing_type=sa.Numeric(precision=15, scale=4),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('products', 'stock_actual',
               existing_type=sa.Numeric(precision=15, scale=4),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('products', 'codigo_barras',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               comment='Código de barras EAN/UPC',
               existing_nullable=True)
    op.alter_column('products', 'unidad_medida',
               existing_type=sa.VARCHAR(length=20),
               comment='unidad, kg, lt, mt, etc.',
               existing_nullable=True)
    op.alter_column('products', 'costo_unitario',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               comment=None,
               existing_comment='Costo de adquisición para margen',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('products', 'precio_neto',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               comment='Precio sin IVA',
               existing_nullable=False)
    op.alter_column('products', 'descripcion',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'codigo_interno',
               existing_type=sa.VARCHAR(length=50),
               comment='SKU / código interno del producto',
               existing_nullable=False)
    op.drop_index(op.f('ix_public_tenant_users_id'), table_name='tenant_users', schema='public')
    op.drop_table('tenant_users', schema='public')
    op.drop_index(op.f('ix_public_tenants_schema_name'), table_name='tenants', schema='public')
    op.drop_index(op.f('ix_public_tenants_rut'), table_name='tenants', schema='public')
    op.drop_index(op.f('ix_public_tenants_id'), table_name='tenants', schema='public')
    op.drop_table('tenants', schema='public')
    op.drop_index(op.f('ix_public_saas_users_id'), table_name='saas_users', schema='public')
    op.drop_index(op.f('ix_public_saas_users_email'), table_name='saas_users', schema='public')
    op.drop_table('saas_users', schema='public')
    op.drop_index(op.f('ix_public_saas_plans_id'), table_name='saas_plans', schema='public')
    op.drop_table('saas_plans', schema='public')
    # ### end Alembic commands ###
